# Generated by Django 5.2.9 on 2025-12-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinedproduct',
            name='save_trm',
            field=models.IntegerField(default=12, help_text='가입 기간 (단위: 개월, 만기일 계산용)'),
        ),
        migrations.AlterField(
            model_name='userjoinedproduct',
            name='amount',
            field=models.BigIntegerField(default=0, help_text='현재 총 예치금액 또는 총 납입액'),
        ),
        migrations.AlterField(
            model_name='userjoinedproduct',
            name='joined_at',
            field=models.DateField(auto_now_add=True, help_text='가입일 (기본값 오늘)'),
        ),
        migrations.AlterField(
            model_name='userjoinedproduct',
            name='monthly_payment',
            field=models.BigIntegerField(default=0, help_text='적금일 경우 월 납입액'),
        ),
    ]
