# Generated by Django 5.2.9 on 2025-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_agent', '0002_userjoinedproduct_save_trm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', '정기예금'), ('saving', '적금')], default='deposit', help_text='상품 유형 (예금 또는 적금)', max_length=10),
        ),
        migrations.AddField(
            model_name='jeonseloanproduct',
            name='search_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
