# Generated by Django 5.2.9 on 2025-12-24 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_agent', '0003_depositproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinedproduct',
            name='intr_rate',
            field=models.FloatField(default=0.0, help_text='적용 금리'),
        ),
        migrations.AddField(
            model_name='userjoinedproduct',
            name='intr_rate_type',
            field=models.CharField(default='S', help_text='금리 유형(S:단리, M:복리)', max_length=10),
        ),
        migrations.AlterField(
            model_name='userjoinedproduct',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='가입일'),
        ),
    ]
